#!/usr/bin/env ruby

require_relative "../lib/secret_number"

begin
  SecretNumber::Application.new(ARGV).run
rescue SecretNumber::IntegerNotFoundError => err
  abort "secret: #{err.message}"
rescue SecretNumber::NoArgumentFoundError => err
  abort "secret: #{err.message}"
end
